name: 02 - Run Azure Metrics Downloader

on:
  workflow_dispatch

jobs:
  download-and-run:
    runs-on: windows-latest  # Using Windows runner since it's a .NET executable

    steps:
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          name: build-artifacts
          workflow: 01-build.yml
          path: ./extracted/
          search_artifacts: true
        
      - name: Run Azure Metrics Downloader
        env:
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        run: |
          # Rem                                                 AzureMetricsDownloader.exe  <<ApplicationId>>               <<Secret>>                          <<TenantId>>                    <<FullResourceID>>                                                                                                                                    <<MetricName>>  <<AgregationType>>  <<ExportFilename>> <<Agregation>>    <<StartDateTime>>  <<StopDateTime>>
          ./extracted/AzureMetricsDownloader/bin/Release/net8.0/AzureMetricsDownloader.exe  ${{ secrets.AZURE_CLIENT_ID }}  ${{ secrets.AZURE_CLIENT_SECRET }}  ${{ secrets.AZURE_TENANT_ID }}  /subscriptions/0af06968-920a-43d9-9931-cfe593e9a041/resourceGroups/sample-app-gateway/providers/Microsoft.Network/applicationGateways/lpm-t-agw-mf01  TotalRequests   Total               export.csv         Totals            2024-10-23_11-00   2024-10-23_15-00
          # Display Results
          Import-Csv ./export.csv | Format-Table 
